const endpointCategory = "products/categories?";
const categoryAttributesPerPage = "&per_page=15";
const categoryAttributesSubCat = "&parent=30";
const categoryAttributesDisplay = "&display=subcategories";
const endpointProducts = "products?";
const endpointSingleProduct = "products/";
const loginEndpoint = 'customers?';
const customersEndpoint = 'customers?';
const authEndpoint = 'wc-auth/v1/authorize';